openapi: 3.0.0
info:
  title: Shush API
  version: 1.0.0
externalDocs:
  url: https://github.com/tivvit/shush
servers:
  - url: https://s/api/v1
paths:
  /urls:
    get: # todo pagination, limit by user, limit by regex
      summary: List all urls
      responses:
        '200':
          description: A JSON array of url details
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Url'
    post:
      summary: Add url
      parameters:
        - in: query
          name: shortener
          schema:
            type: string
            enum: ["generator", "hash"]
          description: shortener algo (may be disabled by the server admin)
        - in: query
          name: algo
          schema:
            type: string
            enum: ["md5", "sha1", "sha256","sha512", "fnv32", "fnv32a",  "fnv64", "fnv64a",  "fnv128",  "fnv128a",  "adler32",  "crc32ieee", "crc64iso",  "crc64ecma"]
          description: valid only for shortener=hash (may be disabled/edited by the server admin)
        - in: query
          name: len
          schema:
            type: integer
            minimum: 1
          description: length of the produced short_url (may be disabled by the server admin)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUrl'
      responses:
        '201':
          description: Created url
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Url'
  /urls/{short_url}:
    get:
      summary: url details
      parameters:
        - name: short_url
          in: path
          required: true
          description: shorturl
          schema:
            type: string
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Url'
        '404':
          description: not found
    put:
      summary: create/update url
      parameters:
        - name: short_url
          in: path
          required: true
          description: shorturl
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Url'
      responses:
        '200':
          description: updated/created url
    delete:
      summary: delete url
      parameters:
        - name: short_url
          in: path
          required: true
          description: shorturl
          schema:
            type: string
      responses:
        '204':
          description: url deleted
components:
  schemas:
    Url:
      properties:
        short_url:
          type: string
        target:
          type: string
        owners:
          type: array
          items:
            type: string
        expiration:
          type: string
          format: date-time
      required:
        - short_url
        - target
      example: {
        "short_url": "g",
        "target": "https://google.com",
        "owners": ["tivvit"],
        "expiration": "2017-07-21T17:32:28Z"
      }
    NewUrl:
      properties:
        target:
          type: string
        owners:
          type: array
          items:
            type: string
        expiration:
          type: string
          format: date-time
      required:
        - target
      example: {
        "target": "https://google.com",
        "owners": ["tivvit"],
        "expiration": "2017-07-21T17:32:28Z"
      }